#!/bin/bash

set -e

print_help() {
    cat <<EOF
To tag a new release:
  script/release <tag-name>
  Example: script/release 0.23.10-18f
EOF
}

if [ $# -eq 0 ]; then
  print_help >&2
  exit 1
fi

tag_name=""

while [ $# -gt 0 ]; do
  case "$1" in
  -h | --help )
    print_help
    exit 0
    ;;
  -* )
    printf "unrecognized flag: %s\n" "$1" >&2
    exit 1
    ;;
  * )
    tag_name="$1"
    shift 1
    ;;
  esac
done

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "refusing to continue due to uncommitted local changes" >&2
  exit 1
fi

echo "Tagging version $tag_name and pushing to GitHub"
echo ""

git checkout main
git pull
git tag -s -m "Releasing $tag_name" v"$tag_name"
git push origin main --tags

echo ""
echo "Done!"
