#!/bin/bash

set -e

print_help() {
    cat <<EOF
To tag a new release:
  script/release <tag-name>
  Example: script/release 0.23.10-18f
EOF
}

# If no argument is provided to the script, print the usage instructions
if [ $# -eq 0 ]; then
  print_help >&2
  exit 1
fi

tag_name=""

# If there is an argument, do the following depending on the argument
while [ $# -gt 0 ]; do
  case "$1" in
  # If the user ran "script/release --help" or "script/release -h", print the usage instructions
  -h | --help )
    print_help
    exit 0
    ;;
  # If the user ran "script/release -t" or any other flag except -h, print an error
  -* )
    printf "unrecognized flag: %s\n" "$1" >&2
    exit 1
    ;;
  # Otherwise, set the tag_name name variable to the argument
  * )
    tag_name="$1"
    shift 1
    ;;
  esac
done

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "refusing to continue due to uncommitted local changes" >&2
  exit 1
fi

echo "Tagging version $tag_name and pushing to GitHub"
echo ""

git checkout main
git pull
git tag -s -m "Releasing $tag_name" v"$tag_name"
git push origin main --tags

echo ""
echo "Done!"
