name: ci
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0, head]
        gemfile: [rails_5.2.gemfile, gemfiles/rails_6.0.gemfile, gemfiles/rails_6.1.gemfile, gemfiles/rails_dev.gemfile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install --gemfile=gemfiles/${{ matrix.gemfile }}
      - run: bundle exec rake
